### ISSUE TITLE
vertically align the bootstrap modals

### ISSUE THREAD

**Issue by potasiyam** [NerdCats/WebCat#50]
Bootstrap modals are top aligned by default. Middle aligned modals get better  attention.

**Comment by thehoneymad** [comment]
This would be a tricky one to be honest. Here's the library we are using for modals.
https://github.com/dougludlow/ng2-bs3-modal

**Comment by potasiyam** [comment]
Well, I used to do this in a flexbox way but it seems that fix messes up with click events, probably layering issue.
``` css
body.modal-open .modal {
  display: flex !important;
  align-items: center;
}
```
Looking for workaround.
